development:
  clients:
    default:
      database: shadid
      hosts:
        - ds149268.mlab.com:49268
      options:
        user: 'root'
        password: 'toor'
  options:

test:
  clients:
    default:
      database: my_app_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1

production:
  clients:
    default:
      database: shadid
      hosts:
        - ds149268.mlab.com:49268
      options:
        user: 'root'
        password: 'toor'
  options:
